run:
  timeout: 1m
linters:
  enable-all: true
  disable:
    - testpackage
    - paralleltest
    - gomnd
    - gochecknoglobals
    - nlreturn
    - exhaustivestruct
    - scopelint
    - wsl
    - gci
    - gofumpt